version: '3'

volumes:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=hemocentro
      - MYSQL_DATABASE=salsa
      - MYSQL_USER=salsa

  app:
    image: openjdk:8-jre
    restart: always
    command: java -jar /target/salsa-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    volumes:
      - ./salsa/target:/target:ro
    depends_on:
      - db
    links:
      - db

  web:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./angular4-client/dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - app